id: 584e8e824f3b40a5a6074446774ec931
initial_creation_type: ocr
source_metadata:
  volumes:
    01f8c2f848dd46a5b1bdb1a2ee2d0268:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ''
      total_pages: 1044
      volume_number: 38
